# Generated by Django 2.1.1 on 2018-09-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tag',
            field=models.CharField(blank=True, choices=[('python', 'python'), ('django', 'django')], max_length=100),
        ),
    ]
