# Generated by Django 2.1.1 on 2018-09-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180922_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tag',
            field=models.CharField(blank=True, choices=[('PYTHON', 'PYTHON'), ('DJANGO', 'DJANGO'), ('JAVA', 'JAVA'), ('MYSQL', 'MYSQL'), ('MACHINE_LEARNING', 'MACHINE_LEARNING'), ('JAVASCRIPT', 'JAVASCRIPT'), ('FRONT_END', 'FRONT_END'), ('C/C++', 'C/C++')], max_length=100),
        ),
    ]
